### ISSUE TITLE
Exporter fails to export batch

### ISSUE THREAD

**Issue by bbetter** [elastic/apm-agent-android#147] opened 2023-04-03 11:26 UTC
After all the configuration 
someway it's not exporting no metrics, spans etc.

How can I get a bit more informative error than the empty string it is currently? :)

W/OkHttpGrpcExporter: Failed to export metrics. Server responded with HTTP status code 404. Error message:

**Comment by LikeTheSalad** [comment] 2023-04-03 13:18
Got it, we'd need to double-check the following:

- The APM endpoint URL is the right one.
- The auth token is provided.

To check them both you can take a look at Kibana's menu, and select "Add Integrations" as shown below

<img src="https://user-images.githubusercontent.com/56847527/229517740-130466e0-1850-425c-bd7b-11b67b5bea33.png" width="200">

Then select "APM"

<img src="https://user-images.githubusercontent.com/56847527/229518239-2dd0544d-c5a3-49ba-916f-303aa7d22973.png" width="400">

Then scroll down until you see these values under "APM Agents":

<img src="https://user-images.githubusercontent.com/56847527/229520179-29dd2fcf-6190-4fd8-bb7f-012240c18460.png" width="400">

If you pick the "Java" tab, you should find the APM URL named `server_url` and the `secret_token` would be your auth token, which you can provide in the Android SDK by creating a Connectivity object with `Connectivity.withSecretToken(url, token)`

If all goes well, usually the data is seen in Kibana a few seconds after it's sent from the device.

Please let me know if questions.

**Comment by LikeTheSalad** [comment] 2023-04-05 10:41
I'm planning to create a release later today, I'll notify here when it's ready

**Comment by LikeTheSalad** [comment] 2023-04-05 12:17
The new version `0.6.0` has been published, although I'd give it an hour or so before trying to fetch it since usually MavenCentral takes some time to make a new release available.

So with this version you can:
- Provide your app's environment at runtime with `ElasticApmConfiguration.setDeploymentEnvironment`, so you will no longer need to create the `co_elastic_apm_android.properties` file.
- Provide your own OpenTelemetry signal processors and exporters through `ElasticApmConfiguration.setSignalConfiguration` which receives [this interface](https://github.com/elastic/apm-agent-android/blob/0247c6b3a3396a76a4fa659eb24c39506b696726/android-sdk/src/main/java/co/elastic/apm/android/sdk/connectivity/opentelemetry/SignalConfiguration.java) where there's a [convenient method](https://github.com/elastic/apm-agent-android/blob/0247c6b3a3396a76a4fa659eb24c39506b696726/android-sdk/src/main/java/co/elastic/apm/android/sdk/connectivity/opentelemetry/SignalConfiguration.java#L55) to provide exporters only.
- We've also set our minSdk to 24.

I'm not aware of any issue when using grpc with the Elastic APM server, however, if that's the case with your setup, then you could try another exporter provided by OTel for [traces and metrics](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp), and one of [these for logs](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp/logs/src/main/java/io/opentelemetry/exporter/otlp).

**Comment by LikeTheSalad** [comment] 2023-04-11 07:57
Hi @bbetter 

Elastic's Connectivity params are used across the 3 OTel exporters ([traces](https://github.com/elastic/apm-agent-android/blob/main/android-sdk/src/main/java/co/elastic/apm/android/sdk/connectivity/opentelemetry/DefaultSignalConfiguration.java#L46), [metrics](https://github.com/elastic/apm-agent-android/blob/main/android-sdk/src/main/java/co/elastic/apm/android/sdk/connectivity/opentelemetry/DefaultSignalConfiguration.java#L64) and [logs](https://github.com/elastic/apm-agent-android/blob/main/android-sdk/src/main/java/co/elastic/apm/android/sdk/connectivity/opentelemetry/DefaultSignalConfiguration.java#L55)) in the way as shown in those links. However, if you override Elastic's provided exporters, then you're going to have to configure their endpoint (and authorization header when needed) by yourself. You can take a look at the links above to get an idea of how to do so with OTel's API, though basically you should just have to call the exporter builder's "setEndpoint" method and pass your APM endoint, which should be the full URL (including the "http(s)://" scheme). That should be enough from OTel exporters' side to connect them to your backend.

Even though you're going to be setting your APM endpoint manually for OTel exporters, you still need to provide the same endpoint in Elastic's `Connectivity` param, so that Elastic-scpecific features that use the same endpoint can work, such as Kibana's [Central configuration](https://www.elastic.co/guide/en/kibana/current/agent-configuration.html#agent-configuration).

After you've set your exporters manually and finished initializing the Elastic SDK, I recommend trying it out by manually sending some signals, [as explained here](https://www.elastic.co/guide/en/apm/agent/android/current/manual-instrumentation.html). Basically, you would have global access to the configured `OpenTelemetry` instance by calling `GlobalOpenTelemetry.get()` or any of its convenience methods, and from then on you can do the same they explain in their manual instrumentation guide on how to [create a span](https://opentelemetry.io/docs/instrumentation/java/manual/#create-spans) or [metric](https://opentelemetry.io/docs/instrumentation/java/manual/#metrics). (they haven't yet updated their docs on creating logs manually because their logs SDK is not yet stable).

I would also recommend checking your app's outgoing network requests using [Android Studio's network inspector](https://developer.android.com/studio/debug/network-profiler), in which you should be able to spot OTel's requests by checking their URL paths, which should start with `/opentelemetry.proto.collector`. If you spot those, it means that OTel's SDK configuration was done properly. However, if for some reason those requests don't succeed, then since you mentioned that you don't need to provide any auth params for your setup, you should raise an issue within the [Elastic APM server repo](https://github.com/elastic/apm-server) explaining how's your backend configuration, version, and any other meaningful information so that they can help you sort this issue.

I hope it helps, please let me know if you have any questions about what I mentioned here.

**Comment by LikeTheSalad** [comment] 2023-04-11 08:06
By the way, one thing I just remembered about network requests issues on Android, is that if your endpoint scheme is `http` (without the 's'), then the network requests to it won't work due to Android's [cleartext traffic being disabled](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted) on Android 9 and above by default. You can enable it if needed by adding this line: `android:usesCleartextTraffic="true"` in your AndroidManifest.xml's `application` tag attrs, like so:

```xml
<application
        android:usesCleartextTraffic="true"
```

**Comment by LikeTheSalad** [comment] 2023-04-19 07:25
Hi @bbetter, in case it helps, please note that OTLP support over GRPC was added to the Elastic APM server on version [7.12](https://www.elastic.co/guide/en/apm/server/current/release-notes-7.12.html#_added_5), and [8.3](https://www.elastic.co/guide/en/apm/guide/current/release-notes-8.3.html#_added_5) for HTTP.

**Comment by LikeTheSalad** [comment] 2023-04-19 14:35
Glad to know it's solved now!

Yes, the client supports w3c trace context propagation. It's configured out of the box for OkHttp requests by using bytecode instrumentation. You would need to add our [Gradle plugin](https://plugins.gradle.org/plugin/co.elastic.apm.android) for the instrumentation to be possible.

I'm going to close this ticket since the issue is solved now, though feel free to reopen it if needed.

**Closed by LikeTheSalad** 2023-04-19 14:35 UTC
Labels: agent-mobile, agent-android, community, triage

**Comment by ty-elastic** [comment] 2023-10-10 21:24
I'm wondering if it makes sense to formally support OTLP/HTTP1.1 output (via a simple config) vs. OTLP/GRTP/HTTP2? HTTP2 can still be a little tricky to get right with proxies and load balancers in between the agents and the APM server.

Per [this](https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html), "For ease of setup, we recommend using OTLP/HTTP when proxying or load balancing requests to the APM Server."
