### ISSUE TITLE
serverUrl, full url support with path

### ISSUE THREAD

**Issue by gjelenc** [elastic/apm-agent-android#187] opened 2023-09-19 10:54 UTC
Is it possible to enable full URL support with a complete path for the serverUrl configuration variable, similar to how it is implemented in the APM (Application Performance Monitoring) JavaScript RUM (Real User Monitoring) agent?

And also config for java.io.IOException Cleartext HTTP traffic.

**Comment by ssitsp** [comment] 2023-09-19 12:41
Offen is backend functionality (in this case apm/open telemetry endpoints) exposed outside over some proxy. 
In my opinion this is an issue!

**Comment by LikeTheSalad** [comment] 2023-09-20 07:35
Hi @gjelenc - You should be able to set a full url with a path with no issues both in the [gradle script](https://www.elastic.co/guide/en/apm/agent/android/current/configuration.html#_gradle_configuration) as well as using the agent's [runtime apis](https://www.elastic.co/guide/en/apm/agent/android/current/configuration.html#app-server-connectivity) as there are no validations in place that prevent doing so. Please let us know if you find any issues!

> And also config for java.io.IOException Cleartext HTTP traffic.

I'm not sure I'm following up regarding this part, however, I do know that Android's latest apis disable cleartext traffic by default, so in case your endpoint needs cleartext traffic to work (for debugging purposes) you could enable it in your app's AndroindManifest.xml file. There are a couple of ways this could be done that are explained [in here](https://stackoverflow.com/a/50834600/7031224).

**Comment by gjelenc** [comment] 2023-09-20 08:49
Ok my gradle config is:
```
elasticApm {
    serverUrl = "https://api.example.si/es/some_path/"
    apiKey = "****"
}
```
And here are log from logcat:
```
2023-09-19 14:19:20.989 17360-17360 InputMethodManager      si.example.myapmapp             I  startInputInner - mService.startInputOrWindowGainedFocus
2023-09-19 14:19:21.498 17360-17583 ELASTIC_AGENT           si.example.myapmapp             D  Creating OkHttp event listener
2023-09-19 14:19:21.499 17360-17583 ELASTIC_AGENT           si.example.myapmapp             I  Intercepting OkHttp request
2023-09-19 14:19:21.499 17360-17583 ELASTIC_AGENT           si.example.myapmapp             D  Intercepting OkHttp request: https://api.example.si/opentelemetry.proto.collector.logs.v1.LogsService/Export
2023-09-19 14:19:21.499 17360-17583 ELASTIC_AGENT           si.example.myapmapp             I  Ignoring OTel exporting related http request
2023-09-19 14:19:21.836 17360-17654 OkHttpGrpcExporter      si.example.myapmapp             W  Failed to export logs. Server responded with HTTP status code 404. Error message: Not Found
2023-09-19 14:19:26.914 17360-17582 ELASTIC_AGENT           si.example.myapmapp             D  Returning true time
2023-09-19 14:19:26.929 17360-17582 ELASTIC_AGENT           si.example.myapmapp             D  Creating OkHttp event listener
2023-09-19 14:19:26.930 17360-17582 ELASTIC_AGENT           si.example.myapmapp             I  Intercepting OkHttp request
2023-09-19 14:19:26.931 17360-17582 ELASTIC_AGENT           si.example.myapmapp             D  Intercepting OkHttp request: https://api.example.si/opentelemetry.proto.collector.metrics.v1.MetricsService/Export
2023-09-19 14:19:26.931 17360-17582 ELASTIC_AGENT           si.example.myapmapp             I  Ignoring OTel exporting related http request
2023-09-19 14:19:27.021 17360-17650 OkHttpGrpcExporter      si.example.myapmapp             W  Failed to export metrics. Server responded with HTTP status code 404. Error message: Not Found
2023-09-19 14:19:32.553 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  Central config url: https://api.example.si/config/v1/agents?service.name=MyAPMApp&service.environment=android-dev
2023-09-19 14:19:32.554 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  Retrieving central config ETag null
2023-09-19 14:19:32.573 17360-17591 TrafficStats            si.example.myapmapp             D  tagSocket(116) with statsTag=0xffffffff, statsUid=-1
2023-09-19 14:19:32.953 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  Storing central config ETag null
2023-09-19 14:19:32.954 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  Central config cache control header not found
2023-09-19 14:19:32.954 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  This APM Server does not support central configuration. Update to APM Server 7.3+
2023-09-19 14:19:32.955 17360-17591 ELASTIC_AGENT           si.example.myapmapp             I  Central config returned max age is null
2023-09-19 14:19:32.955 17360-17591 ELASTIC_AGENT           si.example.myapmapp             I  Scheduling next central config poll
2023-09-19 14:19:32.956 17360-17591 ELASTIC_AGENT           si.example.myapmapp             D  Next central config poll in 60 seconds
```
You can see warnings: `Failed to export metrics. Server responded with HTTP status code 404. Error message: Not Found` 
And URL: `https://api.example.si/config/v1/agents?service.name=MyAPMApp&service.environment=android-dev`
which is wrong, 
it has to be: `https://api.example.si/es/some_path/config/v1/agents?service.name=MyAPMApp&service.environment=android-dev`

**Comment by LikeTheSalad** [comment] 2023-09-20 09:18
Thank you for the detailed information. I'll have a look at it.

**Comment by LikeTheSalad** [comment] 2023-09-20 15:09
I realized that the initial path was indeed being removed in 2 places:

* The Elastic's central config setup, which should be fixed in https://github.com/elastic/apm-agent-android/pull/189
* OTel's gRPC exporter.

For OTel's gRPC exporter, I created [this PR](https://github.com/open-telemetry/opentelemetry-java/pull/5841) that should fix it, however, I'm not sure if replacing the initial path is actually an expected behavior in OTel, so I'm going to wait for some feedback on their side before proceeding to merge [this other PR](https://github.com/elastic/apm-agent-android/pull/189).

Thank you for your feedback.

**Comment by LikeTheSalad** [comment] 2023-09-28 09:41
They mentioned in [this PR](https://github.com/open-telemetry/opentelemetry-java/pull/5841) that, when using gRPC, this is an expected behavior. I'm still planning to merge this [other PR](https://github.com/elastic/apm-agent-android/pull/189) since it's related to Elastic's central config and doesn't work with gRPC. It seems like you might be able to have a server with an initial path as long as you use HTTP instead of gRPC by setting an HTTP exporter such as [OtlpHttpSpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/1bd41e2b790e22e148d013e3287588317e01997b/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporter.java#L21) for example, you could do so by setting a custom `SignalConfiguration` in the `ElasticApmConfiguration` object where you'd provide all 3 http exporters like so:

```java
ElasticApmConfiguration config = ElasticApmConfiguration.builder()
        .setSignalConfiguration(SignalConfiguration.custom(httpSpanExporter, httpLogExporter, httpMetricExporter))
        .build();
ElasticApmAgent.initialize(context, config);
```

Just be aware that the Elastic APM server's OTLP over HTTP support was added on version [8.3.0](https://www.elastic.co/guide/en/apm/guide/current/release-notes-8.3.html#_added_8).

**Comment by LikeTheSalad** [comment] 2023-10-19 09:38
The non-OTel part of this issue is fixed by https://github.com/elastic/apm-agent-android/pull/189 which is already merged, so I'm closing this issue.

**Closed by LikeTheSalad** 2023-10-19 09:38 UTC
Labels: agent-mobile, agent-android, community, triage
